### ISSUE TITLE
Ability to Filter or Smooth the Output

### ISSUE THREAD

**Issue by AmateurAtAllThis** [EverythingSmartHome/mqtt-bed-sensor#1]
First off, thank you to EverythingSmartHome for putting this together.  I have implemented this project and it works perfectly 99% of the time.  I am experiencing large (>100Kg) spikes with no weight on the bed.  Home Assistant reports these spike as occurring for less than a minute.  Assuming I have not done something wrong (which takes a leap of faith on my part), do you have any suggestions for smoothing out these outlier readings?

Thanks in advance for all the time and effort!

**Comment by EverythingSmartHome** [comment]
No problem, so glad you got everything working!

How often are you sending data to Home Assistant at the moment? I have seen something like this but not for as long as a minute, just one reading can spike then come down which makes it easy to ignore.

**Comment by AmateurAtAllThis** [comment]
I have left the default that was in your code.  So, I believe it is three seconds.  I was guessing regarding the duration of the spike; it may be far less than a minute.  I have attached a screenshot from home assistant.  The bed was not touched during the timeline shown.  Assuming I am only receiving a single errant reading, how should I go about ignoring it?  Thanks again.

<img width="1176" alt="Screen Shot 2019-09-20 at 12 51 27 AM" src="https://user-images.githubusercontent.com/38384804/65300248-d174e680-db40-11e9-90d3-6995e3b22cc9.png">

**Comment by EverythingSmartHome** [comment]
That looks excellent well done! I believe it is a single reading, so if you do not need the readings to be every 3 seconds, I'd suggest maybe going for 10 seconds or more depending on how often you need readings. Try 10 seconds if suitable and see if that gives you better readings?

**Comment by EverythingSmartHome** [comment]
No response, so will close for now.
