### ISSUE TITLE
Weight 10 times too high?

### ISSUE THREAD

**Issue by koelkast88** [EverythingSmartHome/mqtt-bed-sensor#2]
Hi Lewis,

Well done, your instructions are clear, and it works well at the test ‘setup’ with a wooden ‘shelf’. Next step should mount it under my bed. Hope the WAF (Wife Acceptance Factor) is high enough to get it working for that goal 🙂

Although, one problem still exist. I adjusted the calibration factor to 2386.
It shows my weight in Home Assistant 10 times higher; 2 kg is 20 kg.

Should I adjust the bed_sensor script?

**Comment by EverythingSmartHome** [comment]
Hi,

Glad you got it working! Yes you just need to adjust the bed_sensor sketch with the calibration factor you worked out in the calibration sketch. This is the intended way to do it!

Hope that helps.
